[tool.poetry]
name = "job-finder-course4-"
version = "0.1.0"
description = ""
authors = ["Dmit Bashmakov <denegniy1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
